### ISSUE TITLE
Magento 2.4.6 jquery migrate

### ISSUE THREAD

**Issue by Demoli** [shipperhq/module-shipper#131]
As of Magento 2.4.6 jquery-migrate has been removed from core library.

Now when I select a checkout shipping method the ShipperHQ ajax call fails.

```
config.js:112 Uncaught TypeError: $.ajax(...).success is not a function
    at Object.reloadConfig (config.js:112:20)
    at UiClass.<anonymous> (shipperhq-calendar.js:293:36)
    at Function.notifySubscribers (knockout.js:1401:50)
    at Function.valueHasMutated (knockout.js:1645:46)
    at Object.observable [as isLoading] (knockout.js:1609:40)
    at Object.getRates (new-address.js:53:33)
    at ko.subscription._callback (shipping-rate-service.js:24:32)
    at Function.notifySubscribers (knockout.js:1401:50)
    at Function.valueHasMutated (knockout.js:1645:46)
    at Object.observable [as shippingAddress] (knockout.js:1609:40)
```

I can see that ajax.success is still used in 3 places
```
vendor/shipperhq/module-calendar/src/view/frontend/web/js/model/config.js
vendor/shipperhq/module-pickup/src/view/frontend/web/js/action/set-shipping-information.js
vendor/shipperhq/module-pickup/src/view/frontend/web/js/model/config.js
```

**Comment by wsajosh** [comment]
Hi @Demoli 

Thanks for raising this, we're aware of the issue and have an internal ticket raised to address it. Our aim is to have a resolution within the next two weeks. We'll update here once the update is available.

**Comment by wsadaniel** [comment]
Hi @Demoli ,

We've released updated versions of the additional ShipperHQ modules you referenced above (`module-calendar` and `module-pickup`) that are compatible with Magento 2.4.6. Please update to the latest versions of these modules.

Regards,
Daniel
